version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=prod
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
